[tool.poetry]
name = "pycharm_external_tools"
version = "0.1.0"
description = ""
authors = ["JD <10216562+joeld1@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
MonkeyType = "^21.5.0"
pyment = {git = "https://github.com/dadadel/pyment.git"}
black = "^21.5b2"
isort = "^5.8.0"
manage-fastapi = "^1.0.0"
poetry-core = "^1.0.3"
project-manager = {git = "https://github.com/joeld1/project-manager.git", rev = "main"}

[tool.poetry.dev-dependencies]
notebook = "^6.4.0"
ipykernel = "^5.5.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
