[tool.poetry.dev-dependencies]
notebook = "^6.4.0"
ipykernel = "^5.5.5"
pre-commit = "^2.13.0"
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
autoflake = "^1.4"
flake8 = "^3.9.2"
mypy = "^0.910"
isort = "^5.9.1"
black = "^21.6b0"
poetry-dynamic-versioning = "^0.13.0"
pipreqs = "^0.4.10"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
pattern = "commit"
bump = true

[tool.poetry-dynamic-versioning.substitution]
enable = true
vcs = "git"
pattern = "commit"

[tool.interrogate]
ignore-init-method = true
ignore-init-module = false
ignore-magic = false
ignore-semiprivate = false
ignore-private = false
ignore-property-decorators = false
ignore-module = false
ignore-nested-functions = false
ignore-nested-classes = true
ignore-setters = false
fail-under = 95
exclude = ["setup.py", "docs", "build"]
ignore-regex = ["^get$", "^mock_.*", ".*BaseClass.*"]
verbose = 0
quiet = false
whitelist-regex = []
color = true
generate-badge = "."
badge-format = "svg"
