[tool.poetry.dependencies]
notebook = "^6.4.0"
ipykernel = "^5.5.5"
pre-commit = {version = "^2.13.0", optional = true}
pytest = {version = "^6.2.4", optional = true}
pytest-cov = {version = "^2.12.1", optional = true}
autoflake = {version = "^1.4", optional = true}
flake8 = {version = "^3.9.2", optional = true}
mypy = {version = "^0.910", optional = true}
isort = {version = "^5.9.1", optional = true}
black = {version = "^21.6b0", optional = true}
poetry-dynamic-versioning = {version = "^0.13.0", optional = true}
pipreqs = {version = "^0.4.10", optional = true}

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
pattern = "commit"
bump = true

[tool.poetry-dynamic-versioning.substitution]
enable = true
vcs = "git"
pattern = "commit"

[tool.interrogate]
ignore-init-method = true
ignore-init-module = false
ignore-magic = false
ignore-semiprivate = false
ignore-private = false
ignore-property-decorators = false
ignore-module = false
ignore-nested-functions = false
ignore-nested-classes = true
ignore-setters = false
fail-under = 95
exclude = ["setup.py", "docs", "build"]
ignore-regex = ["^get$", "^mock_.*", ".*BaseClass.*"]
verbose = 0
quiet = false
whitelist-regex = []
color = true
generate-badge = "."
badge-format = "svg"

[tool.poetry.extras]
dev_tools = ["pytest", "pytest-cov", "autoflake", "flake8", "mypy", "pre-commit", "black", "isort", "notebook", "ipykernel", "pipreqs", "wily", "poetry-dynamic-versioning", "interrogate"]

# poetry add --optional notebook --optional ipykernel --optional pre-commit --optional pytest --optional pytest-cov --optional autoflake --optional flake8 --optional mypy --optional isort --optional black --optional "interrogate[png]" --optional wily
# poetry remove -D notebook -D ipykernel -D pre-commit -D pytest -D pytest-cov -D autoflake -D flake8 -D mypy -D isort -D black -D poetry-dynamic -D pipreqs -D wily -D interrogate
